modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Vazkii/Quark"

[[mods]]
modId="quark"
displayName="Quark"
version="${version}"
authors="Vazkii, Wiiv, WireSegal, MCVinnyq"
description='''
Small things.
'''

[[dependencies.quark]]
    modId="autoreglib"
    mandatory=true
    versionRange="[1.4-34,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.quark]]
    modId="forge"
    mandatory=true
    versionRange="[28.1.61,)"
    ordering="AFTER"
    side="BOTH"